db:
  name: crypto
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: "123456"
  database: crypto
  synchronize: true
  logging: false
  entities: [dist/entity/*.js]
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 1
jwt:
  secret: '123456789'
  expiresIn: 259200